title: Alauda Streaming Service for RabbitMQ
logoText: Alauda Streaming Service for RabbitMQ
lang: zh
api:
  crds:
    - docs/shared/crds/*.yaml
  openapis:
    - docs/shared/openapis/*.json
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml
